/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package actividadobligatoria4parte3;

/**
 *
 * @author Gero Santacruz
 */
public class Ventana1 extends javax.swing.JFrame {

    /**
     * Creates new form Ventana1
     */
    public Ventana1() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Ejercicio 1");
        this.setSize(600,340);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        button1 = new java.awt.Button();
        jButton6 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();

        button1.setLabel("button1");

        jButton6.setText("boton 20");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton24.setText("boton 22");

        jButton3.setText("jButton3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 300));
        getContentPane().setLayout(null);

        jButton9.setText("boton 4");
        getContentPane().add(jButton9);
        jButton9.setBounds(480, 0, 120, 60);

        jButton27.setText("boton 5");
        getContentPane().add(jButton27);
        jButton27.setBounds(0, 60, 120, 60);

        jButton28.setText("boton 15");
        getContentPane().add(jButton28);
        jButton28.setBounds(0, 180, 120, 60);

        jButton29.setText("boton 10");
        getContentPane().add(jButton29);
        jButton29.setBounds(0, 120, 120, 60);

        jButton30.setText("boton 20");
        getContentPane().add(jButton30);
        jButton30.setBounds(0, 240, 120, 60);

        jButton1.setText("boton 0");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(0, 0, 120, 60);

        jButton2.setText("boton 1");
        getContentPane().add(jButton2);
        jButton2.setBounds(120, 0, 120, 60);

        jButton4.setText("boton 22");
        getContentPane().add(jButton4);
        jButton4.setBounds(240, 240, 120, 60);

        jButton5.setText("boton 24");
        getContentPane().add(jButton5);
        jButton5.setBounds(480, 240, 120, 60);

        jButton7.setText("boton 11");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(120, 120, 120, 60);

        jButton8.setText("boton 2");
        getContentPane().add(jButton8);
        jButton8.setBounds(240, 0, 120, 60);

        jButton10.setText("boton 6");
        getContentPane().add(jButton10);
        jButton10.setBounds(120, 60, 120, 60);

        jButton11.setText("boton 16");
        getContentPane().add(jButton11);
        jButton11.setBounds(120, 180, 120, 60);

        jButton12.setText("boton 21");
        getContentPane().add(jButton12);
        jButton12.setBounds(120, 240, 120, 60);

        jButton13.setText("boton 7");
        getContentPane().add(jButton13);
        jButton13.setBounds(240, 60, 120, 60);

        jButton14.setText("boton 12");
        getContentPane().add(jButton14);
        jButton14.setBounds(240, 120, 120, 60);

        jButton15.setText("boton 17");
        getContentPane().add(jButton15);
        jButton15.setBounds(240, 180, 120, 60);

        jButton16.setText("boton 3");
        getContentPane().add(jButton16);
        jButton16.setBounds(360, 0, 120, 60);

        jButton17.setText("boton 8");
        getContentPane().add(jButton17);
        jButton17.setBounds(360, 60, 120, 60);

        jButton18.setText("boton 13");
        getContentPane().add(jButton18);
        jButton18.setBounds(360, 120, 120, 60);

        jButton19.setText("boton 18");
        getContentPane().add(jButton19);
        jButton19.setBounds(360, 180, 120, 60);

        jButton20.setText("boton 23");
        getContentPane().add(jButton20);
        jButton20.setBounds(360, 240, 120, 60);

        jButton21.setText("boton 9");
        getContentPane().add(jButton21);
        jButton21.setBounds(480, 60, 120, 60);

        jButton22.setText("boton 14");
        getContentPane().add(jButton22);
        jButton22.setBounds(480, 120, 120, 60);

        jButton23.setText("boton 19");
        getContentPane().add(jButton23);
        jButton23.setBounds(480, 180, 120, 60);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    // End of variables declaration//GEN-END:variables
}
